name: Build and Upload Bahmni-java-utils artifact

on:
  push:
    branches:
      - master
      - 'BAH-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: |
          mvn clean package -DattachMuleSources -Pgithub deploy
        env:
          GITHUB_USER_REF: ${{ secrets.DOCKER_HUB_USERNAME }}
          GITHUB_TOKEN_REF: ${{ secrets.GITHUB_TOKEN }}

